export type TestId = "PHQ9" | "GAD7" | "DASS21" | "PCL5" | "DESII" | "ACE" | "SDS" | "SWLS" | "MEQ30" | "PERMA" | "EBI" | "CEQ" | "CBI" | "AQ10" | "AQ50" | "CATQ" | "ASRS";

export type TestCategory = "clinico" | "trauma" | "bienestar" | "neurodiversidad" | "postsesion";

export const CATEGORY_LABELS: Record<TestCategory, { title: string; description: string }> = {
  clinico:         { title: "Tamizaje clínico",        description: "Síntomas, deterioro funcional y bienestar laboral" },
  trauma:          { title: "Trauma y disociación",     description: "Estrés postraumático, disociación y adversidad temprana" },
  bienestar:       { title: "Bienestar y florecimiento", description: "Satisfacción con la vida y dimensiones del bienestar" },
  neurodiversidad: { title: "Neurodiversidad",           description: "Perfil autista, enmascaramiento y TDAH en adultos" },
  postsesion:      { title: "Post-sesión",               description: "Para completar después de sesiones con estados no ordinarios de conciencia" },
};

export const CATEGORY_ORDER: TestCategory[] = ["clinico", "trauma", "bienestar", "neurodiversidad", "postsesion"];

export interface ScaleOption {
  value: number;
  short: string;
  full: string;
}

export interface Band {
  max: number;
  label: string;
  description: string;
  textClass: string;
  barClass: string;
}

export interface SubScale {
  label: string;
  indices: number[];
  multiplier?: number;
  maxScore: number;
  bands: { max: number; label: string; textClass: string }[];
}

export interface TestConfig {
  name: string;
  subtitle: string;
  cardDescription: string;
  accentClass: string;
  borderClass: string;
  btnSelectedClass: string;
  btnHoverClass: string;
  barClass: string;
  questions: string[];
  shortLabels: string[];
  instructions: string;
  scale: ScaleOption[];
  computeScore: (answers: number[]) => number;
  maxScore: number;
  minScore: number;
  bands: Band[];
  subScales?: SubScale[];
  disclaimer: string;
  note?: string;
  category: TestCategory;
}

const B = {
  mint:  { textClass: "text-brand-mint",  barClass: "bg-brand-mint" },
  teal:  { textClass: "text-brand-teal",  barClass: "bg-brand-teal" },
  gold:  { textClass: "text-brand-gold",  barClass: "bg-brand-gold" },
  red:   { textClass: "text-red-400",     barClass: "bg-red-400" },
  mid:   { textClass: "text-brand-mid",   barClass: "bg-brand-mid" },
};

const DASS_SCALE: ScaleOption[] = [
  { value: 0, short: "Nunca", full: "No me ocurrió" },
  { value: 1, short: "Poco",  full: "A veces" },
  { value: 2, short: "Bastante", full: "Bastante veces" },
  { value: 3, short: "Mucho", full: "Casi siempre" },
];

export const TEST_CONFIGS: Record<TestId, TestConfig> = {
  PHQ9: {
    name: "PHQ-9",
    subtitle: "Depresión",
    category: "clinico",
    cardDescription: "9 preguntas · ~2 min · Evalúa la presencia y severidad de síntomas depresivos.",
    accentClass: "text-interactive-text",
    borderClass: "border-brand-teal/40 hover:border-brand-teal",
    btnSelectedClass: "bg-brand-teal border-brand-teal text-white",
    btnHoverClass: "hover:border-brand-teal/50 hover:text-brand-teal",
    barClass: "bg-brand-teal",
    questions: [
      "Poco interés o placer en hacer las cosas",
      "Sentirse decaído/a, deprimido/a o sin esperanzas",
      "Con dificultad para quedarse o permanecer dormido/a, o dormir demasiado",
      "Sentirse cansado/a o con poca energía",
      "Con poco apetito o comiendo en exceso",
      "Sintiéndose mal consigo mismo/a — o sintiéndose un fracaso",
      "Con dificultad para concentrarse en cosas como leer o ver televisión",
      "¿Se ha movido o hablado tan lento que otras personas lo noten? O lo contrario: muy inquieto/a",
      "Pensamientos de que estaría mejor muerto/a o de hacerse daño",
    ],
    shortLabels: [
      "Poco interés o placer", "Ánimo deprimido", "Sueño alterado",
      "Fatiga", "Apetito alterado", "Baja autoestima",
      "Concentración", "Lentitud o agitación", "Pensamientos de daño",
    ],
    instructions: "En las últimas dos semanas, ¿con qué frecuencia te han molestado los siguientes problemas?",
    scale: [
      { value: 0, short: "Nunca", full: "Ningún día" },
      { value: 1, short: "Varios", full: "Varios días" },
      { value: 2, short: "Mitad", full: "Más de la mitad" },
      { value: 3, short: "Siempre", full: "Casi todos los días" },
    ],
    computeScore: (a) => a.reduce((s, x) => s + x, 0),
    maxScore: 27,
    minScore: 0,
    bands: [
      { max: 4,  label: "Mínima",               ...B.mint, description: "Los síntomas depresivos son muy leves o ausentes. El bienestar emocional parece estar mayormente preservado." },
      { max: 9,  label: "Leve",                 ...B.teal, description: "Hay algunas dificultades presentes que merecen atención, aunque son manejables por el momento." },
      { max: 14, label: "Moderada",             ...B.gold, description: "Síntomas de intensidad moderada que probablemente están afectando áreas importantes de tu vida cotidiana." },
      { max: 19, label: "Moderadamente severa", ...B.gold, description: "Los síntomas son significativos. El acompañamiento profesional puede marcar una diferencia real." },
      { max: 27, label: "Severa",               ...B.red,  description: "El nivel de síntomas es alto. Es importante buscar apoyo profesional lo antes posible." },
    ],
    disclaimer: "El PHQ-9 es una herramienta de tamizaje clínico, no un diagnóstico definitivo.",
  },

  GAD7: {
    name: "GAD-7",
    subtitle: "Ansiedad",
    category: "clinico",
    cardDescription: "7 preguntas · ~1 min · Identifica y mide la severidad del trastorno de ansiedad generalizada.",
    accentClass: "text-accent-text",
    borderClass: "border-brand-gold/40 hover:border-brand-gold",
    btnSelectedClass: "bg-brand-gold border-brand-gold text-brand-night",
    btnHoverClass: "hover:border-brand-gold/50 hover:text-brand-gold",
    barClass: "bg-brand-gold",
    questions: [
      "Sentirse nervioso/a, ansioso/a o muy alterado/a",
      "No poder dejar de preocuparse o no poder controlar la preocupación",
      "Preocuparse demasiado por diferentes cosas",
      "Dificultad para relajarse",
      "Estar tan inquieto/a que es difícil permanecer sentado/a tranquilamente",
      "Enojarse o irritarse fácilmente",
      "Sentir miedo, como si algo terrible fuera a ocurrir",
    ],
    shortLabels: [
      "Nerviosismo o tensión", "Preocupación incontrolable", "Preocupación excesiva",
      "Dificultad para relajarse", "Inquietud o agitación", "Irritabilidad",
      "Miedo anticipatorio",
    ],
    instructions: "En las últimas dos semanas, ¿con qué frecuencia te han molestado los siguientes problemas?",
    scale: [
      { value: 0, short: "Nunca",   full: "Ningún día" },
      { value: 1, short: "Varios",  full: "Varios días" },
      { value: 2, short: "Mitad",   full: "Más de la mitad" },
      { value: 3, short: "Siempre", full: "Casi todos los días" },
    ],
    computeScore: (a) => a.reduce((s, x) => s + x, 0),
    maxScore: 21,
    minScore: 0,
    bands: [
      { max: 4,  label: "Mínima",   ...B.mint, description: "Los síntomas de ansiedad son muy leves o prácticamente ausentes en este momento." },
      { max: 9,  label: "Leve",     ...B.teal, description: "Hay cierto nivel de activación ansiosa presente que merece atención para evitar que se intensifique." },
      { max: 14, label: "Moderada", ...B.gold, description: "Ansiedad de intensidad moderada que probablemente afecta tu descanso, concentración o relaciones." },
      { max: 21, label: "Severa",   ...B.red,  description: "El nivel de ansiedad es alto. Trabajar con el sistema nervioso con apoyo profesional puede traer alivio real." },
    ],
    disclaimer: "El GAD-7 es una herramienta de tamizaje clínico, no un diagnóstico definitivo.",
  },

  DASS21: {
    name: "DASS-21",
    subtitle: "Depresión · Ansiedad · Estrés",
    category: "clinico",
    cardDescription: "21 preguntas · ~5 min · Evalúa simultáneamente depresión, ansiedad y estrés con tres subescalas.",
    accentClass: "text-interactive-text",
    borderClass: "border-brand-mint/40 hover:border-brand-mint",
    btnSelectedClass: "bg-brand-mint border-brand-mint text-brand-night",
    btnHoverClass: "hover:border-brand-mint/50 hover:text-brand-mint",
    barClass: "bg-brand-mint",
    questions: [
      "Me costó mucho relajarme",
      "Me di cuenta que tenía la boca seca",
      "No podía sentir ningún sentimiento positivo",
      "Se me hizo difícil respirar",
      "Se me hizo difícil tomar la iniciativa para hacer cosas",
      "Reaccioné exageradamente en ciertas situaciones",
      "Sentí que mis manos temblaban",
      "Sentí que tenía muchos nervios",
      "Estaba preocupado/a por situaciones en que podía entrar en pánico o hacer el ridículo",
      "Sentí que no tenía nada por qué vivir",
      "Noté que me agitaba",
      "Se me hizo difícil relajarme",
      "Me sentí triste y deprimido/a",
      "No toleré nada que no me dejara continuar con lo que estaba haciendo",
      "Sentí que estaba al punto de pánico",
      "No me pude entusiasmar por nada",
      "Sentí que valía muy poco como persona",
      "Sentí que estaba muy irritable",
      "Sentí los latidos de mi corazón sin haber hecho esfuerzo físico",
      "Tuve miedo sin razón",
      "Sentí que la vida no tenía ningún sentido",
    ],
    shortLabels: [
      "Relajación", "Boca seca", "Sentimientos positivos ausentes", "Dificultad respirar",
      "Iniciativa", "Reacciones exageradas", "Manos temblando", "Nervios",
      "Miedo al ridículo", "Sin razón para vivir", "Agitación", "Relajarse",
      "Tristeza", "Intolerancia", "Pánico", "Entusiasmo", "Autoestima",
      "Irritabilidad", "Palpitaciones", "Miedo sin razón", "Sin sentido de vida",
    ],
    instructions: "Durante la última semana, ¿con qué frecuencia te ocurrieron las siguientes situaciones?",
    scale: DASS_SCALE,
    computeScore: (a) => a.reduce((s, x) => s + x, 0),
    maxScore: 63,
    minScore: 0,
    bands: [
      { max: 20, label: "Rango bajo",    ...B.mint, description: "Los puntajes globales sugieren baja carga sintomática en las tres dimensiones evaluadas." },
      { max: 35, label: "Rango medio",   ...B.teal, description: "Hay síntomas presentes que merecen atención. Las subescalas muestran dónde se concentra la carga." },
      { max: 50, label: "Rango alto",    ...B.gold, description: "Carga sintomática significativa. El acompañamiento profesional puede hacer una diferencia importante." },
      { max: 63, label: "Rango muy alto", ...B.red, description: "Nivel de síntomas elevado en una o más dimensiones. Se recomienda buscar apoyo profesional pronto." },
    ],
    subScales: [
      {
        label: "Depresión",
        indices: [2, 4, 9, 12, 15, 16, 20],
        multiplier: 2,
        maxScore: 42,
        bands: [
          { max: 9,  label: "Normal", textClass: B.mint.textClass },
          { max: 13, label: "Leve",   textClass: B.teal.textClass },
          { max: 20, label: "Moderada", textClass: B.gold.textClass },
          { max: 27, label: "Severa", textClass: B.gold.textClass },
          { max: 42, label: "Ext. severa", textClass: B.red.textClass },
        ],
      },
      {
        label: "Ansiedad",
        indices: [1, 3, 6, 8, 14, 18, 19],
        multiplier: 2,
        maxScore: 42,
        bands: [
          { max: 7,  label: "Normal", textClass: B.mint.textClass },
          { max: 9,  label: "Leve",   textClass: B.teal.textClass },
          { max: 14, label: "Moderada", textClass: B.gold.textClass },
          { max: 19, label: "Severa", textClass: B.gold.textClass },
          { max: 42, label: "Ext. severa", textClass: B.red.textClass },
        ],
      },
      {
        label: "Estrés",
        indices: [0, 5, 7, 10, 11, 13, 17],
        multiplier: 2,
        maxScore: 42,
        bands: [
          { max: 14, label: "Normal", textClass: B.mint.textClass },
          { max: 18, label: "Leve",   textClass: B.teal.textClass },
          { max: 25, label: "Moderado", textClass: B.gold.textClass },
          { max: 33, label: "Severo", textClass: B.gold.textClass },
          { max: 42, label: "Ext. severo", textClass: B.red.textClass },
        ],
      },
    ],
    disclaimer: "El DASS-21 es una herramienta de investigación y tamizaje clínico (UNSW, uso no comercial).",
  },

  PCL5: {
    name: "PCL-5",
    subtitle: "TEPT / Trauma",
    category: "trauma",
    cardDescription: "20 preguntas · ~5 min · Evalúa síntomas de estrés postraumático basado en el DSM-5.",
    accentClass: "text-foreground/70",
    borderClass: "border-brand-mid/40 hover:border-brand-mid",
    btnSelectedClass: "bg-brand-mid border-brand-mid text-white",
    btnHoverClass: "hover:border-brand-mid/50 hover:opacity-100",
    barClass: "bg-brand-mid",
    questions: [
      "Recuerdos repetidos, perturbadores e involuntarios de la experiencia",
      "Sueños perturbadores relacionados con la experiencia",
      "Sentir o actuar de repente como si la experiencia estuviera ocurriendo de nuevo (flashback)",
      "Sentirte muy alterado/a cuando algo te recuerda la experiencia",
      "Reacciones físicas intensas cuando algo te recuerda la experiencia (palpitaciones, sudoración, etc.)",
      "Evitar recuerdos, pensamientos o sentimientos relacionados con la experiencia",
      "Evitar personas, lugares o situaciones que te recuerden la experiencia",
      "Problemas para recordar partes importantes de la experiencia",
      "Creencias negativas fuertes sobre ti mismo/a, los demás o el mundo",
      "Culparte a ti mismo/a o a otros por lo que ocurrió",
      "Sentimientos negativos intensos (miedo, horror, ira, culpa, vergüenza)",
      "Perder el interés en actividades que antes disfrutabas",
      "Sentirte distante o separado/a de las personas a tu alrededor",
      "Dificultad para experimentar sentimientos positivos (alegría, amor)",
      "Conducta irritable o exabruptos de enojo",
      "Asumir riesgos o comportarse de manera que pueda causarte daño",
      "Estar supercalerto/a, vigilante o en guardia constantemente",
      "Sobresaltarte fácilmente con ruidos u otras cosas",
      "Dificultad para concentrarte",
      "Problemas para dormir",
    ],
    shortLabels: [
      "Recuerdos intrusivos", "Sueños perturbadores", "Flashbacks", "Angustia ante recordatorios",
      "Reacciones físicas", "Evitación interna", "Evitación externa", "Amnesia traumática",
      "Creencias negativas", "Autoinculpación", "Emociones negativas", "Pérdida de interés",
      "Distanciamiento", "Embotamiento afectivo", "Irritabilidad", "Conductas de riesgo",
      "Hipervigilancia", "Sobresalto", "Concentración", "Sueño",
    ],
    instructions: "En el último mes, ¿cuánto le han molestado los siguientes problemas relacionados con una experiencia estresante o traumática del pasado?",
    scale: [
      { value: 0, short: "Nada",   full: "En absoluto" },
      { value: 1, short: "Poco",   full: "Un poco" },
      { value: 2, short: "Algo",   full: "Moderadamente" },
      { value: 3, short: "Bastante", full: "Bastante" },
      { value: 4, short: "Mucho",  full: "Extremadamente" },
    ],
    note: "Piensa en una experiencia estresante o perturbadora del pasado mientras respondes estas preguntas.",
    computeScore: (a) => a.reduce((s, x) => s + x, 0),
    maxScore: 80,
    minScore: 0,
    bands: [
      { max: 20, label: "Sin síntomas significativos", ...B.mint, description: "Los síntomas de estrés postraumático son bajos o ausentes en este momento." },
      { max: 32, label: "Síntomas leves",              ...B.teal, description: "Presencia de síntomas leves que pueden beneficiarse de exploración." },
      { max: 49, label: "Síntomas moderados",          ...B.gold, description: "Nivel sintomático moderado. El acompañamiento especializado en trauma puede ser muy útil." },
      { max: 80, label: "Síntomas severos",            ...B.red,  description: "Puntaje ≥33 sugiere TEPT probable. Se recomienda evaluación clínica especializada." },
    ],
    disclaimer: "El PCL-5 es un instrumento de tamizaje del VA (dominio público). No reemplaza una evaluación clínica especializada en trauma.",
  },

  DESII: {
    name: "DES-II",
    subtitle: "Disociación",
    category: "trauma",
    cardDescription: "28 preguntas · ~7 min · Mide experiencias disociativas en la vida cotidiana (porcentaje de tiempo).",
    accentClass: "text-interactive-text",
    borderClass: "border-brand-teal/30 hover:border-brand-teal",
    btnSelectedClass: "bg-brand-teal border-brand-teal text-white",
    btnHoverClass: "hover:border-brand-teal/50 hover:text-brand-teal",
    barClass: "bg-brand-teal",
    questions: [
      "Conducir o viajar y de repente no recordar parte o todo el trayecto",
      "Escuchar a alguien hablar y darse cuenta de que no captaste parte de lo que dijo",
      "Encontrarte en un lugar y no saber cómo llegaste ahí",
      "Encontrarte usando ropa diferente a la que recuerdas haber puesto",
      "Encontrar escritura, dibujos u objetos entre tus cosas que debes haber hecho pero no recuerdas",
      "No reconocer a amigos o familiares",
      "Sentir como si estuvieras parado/a a tu lado mirándote desde fuera de tu cuerpo",
      "Que te digan que a veces no reconoces a personas cercanas",
      "No tener ningún recuerdo de eventos importantes de tu vida (como una boda o graduación)",
      "Ser acusado/a de mentir cuando sientes que estás diciendo la verdad",
      "Sentir que tu cuerpo no te pertenece",
      "Sentir que las personas, objetos y el mundo a tu alrededor no son reales",
      "Sentir que tu cuerpo no parece pertenecer a ti",
      "Recordar un evento pasado con tanta viveza que sientes que lo estás reviviendo",
      "No estar seguro/a si algo que recuerdas realmente ocurrió o solo lo soñaste",
      "Estar tan absorto/a en una fantasía o ensoñación que sientes que realmente está pasando",
      "Hacer algo pero no saber por qué lo estás haciendo",
      "Mirar al vacío, perderte en tus pensamientos sin ser consciente del tiempo que pasa",
      "Hablar en voz alta contigo mismo/a cuando estás solo/a",
      "Comportarte de manera muy diferente en distintas situaciones, como siendo una persona diferente",
      "Sentir que las personas y el mundo a tu alrededor no son reales",
      "Sentir que estás en un lugar pero también en otro al mismo tiempo",
      "Mirar al espejo y no reconocer a la persona que ves",
      "Percibir cosas que ves como si no fueran reales, aunque sabes que sí lo son",
      "No poder recordar si hiciste algo o solo pensaste en hacerlo",
      "Encontrar evidencia de que hiciste cosas de las cuales no tienes recuerdo",
      "Encontrar escritura o dibujos que debes haber hecho pero no puedes recordar haberlos hecho",
      "Escuchar voces en tu cabeza que te dicen que hagas cosas o que comentan lo que estás haciendo",
    ],
    shortLabels: [
      "Amnesia en viaje", "Pérdidas auditivas", "Amnesia de lugar", "Cambio de ropa", "Escritura sin recuerdo",
      "No reconocer personas", "Salir del cuerpo", "Acusado de no reconocer", "Amnesia de eventos importantes",
      "Acusado de mentir", "Cuerpo ajeno", "Mundo irreal", "Cuerpo no propio", "Revivir el pasado",
      "Confusión sueño/realidad", "Absorción en fantasías", "Actos sin motivo", "Pérdida de tiempo",
      "Hablar solo", "Identidad múltiple", "Mundo irreal (dup.)", "Doble presencia", "No reconocerse en espejo",
      "Cosas que no parecen reales", "Duda sobre acciones", "Evidencia de actos sin recuerdo",
      "Escritura/dibujos sin recuerdo", "Voces internas",
    ],
    instructions: "Las siguientes son experiencias que algunas personas tienen en su vida cotidiana. Indica qué porcentaje del tiempo tienes cada experiencia.",
    scale: Array.from({ length: 11 }, (_, i) => ({
      value: i,
      short: `${i * 10}%`,
      full: `${i * 10}%`,
    })),
    computeScore: (a) => Math.round((a.reduce((s, x) => s + x, 0) / a.length) * 10),
    maxScore: 100,
    minScore: 0,
    bands: [
      { max: 15, label: "Dentro de lo normal", ...B.mint, description: "El nivel de experiencias disociativas está dentro del rango esperado para la población general." },
      { max: 29, label: "Leve",                ...B.teal, description: "Algunas experiencias disociativas presentes, lo que puede ser normal o relacionado con estrés." },
      { max: 49, label: "Moderada",            ...B.gold, description: "Nivel moderado de disociación que puede merecer exploración con un especialista en trauma." },
      { max: 100, label: "Significativa",      ...B.red,  description: "Puntaje ≥30 sugiere disociación clínicamente significativa. Se recomienda evaluación especializada." },
    ],
    disclaimer: "El DES-II es de dominio público (Carlson & Putnam). El puntaje es el promedio de tus respuestas expresado en porcentaje.",
  },

  ACE: {
    name: "ACE",
    subtitle: "Experiencias adversas en la infancia",
    category: "trauma",
    cardDescription: "10 preguntas · ~2 min · Evalúa experiencias adversas antes de los 18 años y su impacto potencial en la salud.",
    accentClass: "text-accent-text",
    borderClass: "border-brand-gold/40 hover:border-brand-gold",
    btnSelectedClass: "bg-brand-gold border-brand-gold text-brand-night",
    btnHoverClass: "hover:border-brand-gold/50 hover:text-brand-gold",
    barClass: "bg-brand-gold",
    questions: [
      "¿Un padre u otra persona en casa te insultaba frecuentemente, te denigraba o te hacía sentir miedo?",
      "¿Un padre u otra persona en casa te empujaba, golpeaba, abofeteaba o lanzaba cosas, dejándote marcas o lastimándote?",
      "¿Un adulto (mayor que tú al menos 5 años) te tocó de manera sexual, o intentó tener relaciones sexuales contigo?",
      "¿Con frecuencia sentías que nadie en tu familia te amaba, o que tu familia no se cuidaba mutuamente?",
      "¿Con frecuencia no tenías suficiente para comer, ropa limpia, o nadie que te protegiera?",
      "¿Alguna vez perdiste a uno de tus padres por divorcio, abandono o alguna otra razón?",
      "¿Tu mamá o madrastra era golpeada, pateada o amenazada físicamente por una pareja?",
      "¿Viviste con alguien que tuviera problemas con el alcohol o usara drogas ilegales?",
      "¿Algún miembro de tu hogar estuvo deprimido, con enfermedad mental, o intentó suicidarse?",
      "¿Algún miembro de tu hogar fue encarcelado?",
    ],
    shortLabels: [
      "Abuso emocional", "Abuso físico", "Abuso sexual", "Negligencia emocional",
      "Negligencia física", "Separación parental", "Violencia doméstica",
      "Alcohol/drogas en casa", "Enfermedad mental en casa", "Encarcelamiento familiar",
    ],
    instructions: "Las siguientes preguntas son sobre experiencias que pueden haber ocurrido durante tu infancia, antes de cumplir los 18 años.",
    note: "Responder estas preguntas puede traer recuerdos difíciles. Tómate el tiempo que necesites y cuídate.",
    scale: [
      { value: 0, short: "No", full: "No" },
      { value: 1, short: "Sí", full: "Sí" },
    ],
    computeScore: (a) => a.reduce((s, x) => s + x, 0),
    maxScore: 10,
    minScore: 0,
    bands: [
      { max: 0,  label: "Sin ACE reportadas",   ...B.mint, description: "No reportas experiencias adversas en la infancia en las categorías evaluadas." },
      { max: 3,  label: "ACE bajas (1-3)",       ...B.teal, description: "Puntajes bajos. Incluso un ACE puede tener impacto; lo importante es el contexto y los factores protectores." },
      { max: 6,  label: "ACE moderadas (4-6)",   ...B.gold, description: "Investigación del CDC muestra que puntajes mayores se asocian a mayor riesgo de problemas de salud física y mental." },
      { max: 10, label: "ACE altas (7+)",         ...B.red,  description: "Puntaje alto. El trauma acumulado en la infancia tiene efectos biológicos reales. El trabajo terapéutico puede marcar diferencia." },
    ],
    disclaimer: "El cuestionario ACE es de dominio público (CDC). Los resultados son orientativos e informativos, no diagnósticos.",
  },

  SDS: {
    name: "SDS",
    subtitle: "Deterioro funcional",
    category: "clinico",
    cardDescription: "3 preguntas · ~1 min · Mide el impacto de los síntomas en el trabajo, la vida social y el hogar.",
    accentClass: "text-interactive-text",
    borderClass: "border-brand-teal/30 hover:border-brand-teal",
    btnSelectedClass: "bg-brand-teal border-brand-teal text-white",
    btnHoverClass: "hover:border-brand-teal/50 hover:text-brand-teal",
    barClass: "bg-brand-teal",
    questions: [
      "Trabajo o estudios",
      "Vida social y de entretenimiento",
      "Vida familiar o responsabilidades domésticas",
    ],
    shortLabels: [
      "Trabajo/estudios", "Vida social", "Vida familiar",
    ],
    instructions: "Usando la escala del 0 al 10, indica qué tanto tus síntomas o dificultades actuales han afectado estas áreas de tu vida:",
    scale: Array.from({ length: 11 }, (_, i) => ({
      value: i,
      short: `${i}`,
      full: i === 0 ? "Sin impacto" : i === 5 ? "Moderado" : i === 10 ? "Extremo" : `${i}`,
    })),
    computeScore: (a) => a.reduce((s, x) => s + x, 0),
    maxScore: 30,
    minScore: 0,
    bands: [
      { max: 4,  label: "Sin deterioro significativo", ...B.mint, description: "Los síntomas tienen poco impacto en las áreas evaluadas." },
      { max: 11, label: "Deterioro leve",              ...B.teal, description: "Algunos síntomas afectan el funcionamiento, aunque de manera manejable." },
      { max: 20, label: "Deterioro moderado",          ...B.gold, description: "Los síntomas están afectando de forma notable el trabajo, la vida social o el hogar." },
      { max: 30, label: "Deterioro severo",            ...B.red,  description: "Impacto significativo en varias áreas de la vida. El apoyo profesional puede ser muy útil." },
    ],
    disclaimer: "La Escala de Deterioro de Sheehan (SDS) es de dominio público (Sheehan). Mide el impacto funcional percibido.",
  },

  SWLS: {
    name: "SWLS",
    subtitle: "Satisfacción con la vida",
    category: "bienestar",
    cardDescription: "5 afirmaciones · ~1 min · Evalúa la satisfacción global con la vida según tu propia valoración.",
    accentClass: "text-interactive-text",
    borderClass: "border-brand-mint/40 hover:border-brand-mint",
    btnSelectedClass: "bg-brand-mint border-brand-mint text-brand-night",
    btnHoverClass: "hover:border-brand-mint/50 hover:text-brand-mint",
    barClass: "bg-brand-mint",
    questions: [
      "En la mayoría de los aspectos, mi vida es cercana a mi ideal",
      "Las condiciones de mi vida son excelentes",
      "Estoy satisfecho/a con mi vida",
      "Hasta ahora he obtenido las cosas importantes que quiero en la vida",
      "Si pudiera vivir mi vida de nuevo, no cambiaría casi nada",
    ],
    shortLabels: [
      "Vida cercana al ideal", "Condiciones de vida", "Satisfacción general",
      "Metas alcanzadas", "Vida sin cambios",
    ],
    instructions: "Indica cuánto acuerdo tienes con cada una de las siguientes afirmaciones sobre tu vida en general:",
    scale: [
      { value: 1, short: "1", full: "Muy en desacuerdo" },
      { value: 2, short: "2", full: "En desacuerdo" },
      { value: 3, short: "3", full: "Algo en desacuerdo" },
      { value: 4, short: "4", full: "Ni de acuerdo ni en desacuerdo" },
      { value: 5, short: "5", full: "Algo de acuerdo" },
      { value: 6, short: "6", full: "De acuerdo" },
      { value: 7, short: "7", full: "Muy de acuerdo" },
    ],
    computeScore: (a) => a.reduce((s, x) => s + x, 0),
    maxScore: 35,
    minScore: 5,
    bands: [
      { max: 9,  label: "Muy insatisfecho/a",       ...B.red,  description: "Puntaje muy bajo. La percepción de la vida en este momento es de fuerte insatisfacción." },
      { max: 14, label: "Insatisfecho/a",            ...B.gold, description: "Insatisfacción notable con la vida. Explorar las áreas de mayor peso puede ser muy útil." },
      { max: 19, label: "Ligeramente insatisfecho/a", ...B.gold, description: "Hay aspectos de la vida que no están funcionando del todo bien para ti." },
      { max: 24, label: "Ni satisfecho/a ni insatisfecho/a", ...B.teal, description: "Zona neutra. Ni claramente positivo ni negativo en la valoración global de tu vida." },
      { max: 29, label: "Ligeramente satisfecho/a",  ...B.teal, description: "En general la vida te parece satisfactoria, con áreas de mejora posible." },
      { max: 34, label: "Satisfecho/a",              ...B.mint, description: "Buena satisfacción general con la vida. Las cosas importantes parecen estar funcionando." },
      { max: 35, label: "Muy satisfecho/a",          ...B.mint, description: "Alta satisfacción con la vida en general. Puntaje en el rango más positivo." },
    ],
    disclaimer: "La SWLS es de libre uso no comercial (Diener et al.). Evalúa satisfacción percibida, no bienestar objetivo.",
  },

  MEQ30: {
    name: "MEQ-30",
    subtitle: "Experiencia mística",
    category: "postsesion",
    cardDescription: "30 preguntas · ~5 min · Evalúa la profundidad e intensidad de una experiencia no ordinaria de conciencia.",
    accentClass: "text-accent-text",
    borderClass: "border-brand-gold/40 hover:border-brand-gold",
    btnSelectedClass: "bg-brand-gold border-brand-gold text-brand-night",
    btnHoverClass: "hover:border-brand-gold/50 hover:text-brand-gold",
    barClass: "bg-brand-gold",
    questions: [
      "Perdiste tu sentido habitual del tiempo",
      "Experimentaste una sensación de unidad con los objetos y personas a tu alrededor",
      "Experimentaste una pérdida de tu sentido habitual de ti mismo/a",
      "Obtuviste una comprensión o entendimiento nuevo",
      "Experimentaste una sensación de contacto sagrado o divino",
      "Experimentaste sensaciones de alegría y bienestar",
      "Sentiste que el universo estaba vivo",
      "Tus experiencias no pudieron expresarse completamente con palabras",
      "Sentiste que tocaste un orden de existencia más profundo o fundamental",
      "El tiempo dejó de ser importante",
      "Experimentaste unidad con toda la humanidad",
      "Sentiste profundo asombro y reverencia",
      "Experimentaste una sensación de unidad con todas las cosas",
      "Sentiste que experimentaste algo que no pudo comunicarse completamente con palabras",
      "El tiempo se aceleró o se detuvo",
      "Obtuviste una visión nueva de lo que es la realidad",
      "Sentiste que la experiencia era sagrada",
      "Tu sentido habitual del tiempo cambió drásticamente",
      "Experimentaste la fusión de tu identidad personal con una totalidad mayor",
      "Sentiste que tus experiencias eran absolutamente ciertas en ese momento",
      "Sentiste paz y tranquilidad",
      "Perdiste el sentido de dónde terminabas tú y comenzaba el mundo exterior",
      "Sentiste maravilla y asombro",
      "Experimentaste eternidad o infinidad",
      "Tuviste experiencias difíciles de describir con palabras",
      "La certeza y el significado de la experiencia permanecieron después",
      "Experimentaste sentimientos de amor",
      "Llegaste a darte cuenta de que toda la humanidad es una en algún nivel fundamental",
      "Sentiste que ya no eras el dueño/a de tus propias experiencias",
      "Sentiste que experimentaste algo nuevo e inefable",
    ],
    shortLabels: [
      "Tiempo perdido", "Unidad con el entorno", "Pérdida del yo", "Nuevo entendimiento",
      "Contacto sagrado", "Alegría y bienestar", "Universo vivo", "Inefabilidad",
      "Orden profundo", "Tiempo sin importancia", "Unidad con humanidad", "Asombro y reverencia",
      "Unidad con todo", "Inefabilidad (2)", "Tiempo alterado", "Nueva visión de la realidad",
      "Sacralidad", "Tiempo drásticamente cambiado", "Fusión identitaria", "Certeza",
      "Paz y tranquilidad", "Borrosidad del yo", "Maravilla", "Eternidad/infinidad",
      "Experiencia indescriptible", "Certeza duradera", "Amor", "Unidad humana",
      "Pérdida de agencia", "Novedad inefable",
    ],
    instructions: "Piensa en una experiencia específica de conciencia no ordinaria (meditación profunda, sesión con sustancias, sueño lúcido, etc.) e indica en qué medida cada afirmación describe esa experiencia:",
    note: "Este instrumento fue diseñado para ser aplicado después de una experiencia. Refleja sobre la experiencia que tengas más presente.",
    scale: [
      { value: 0, short: "0", full: "Nada / nunca" },
      { value: 1, short: "1", full: "Levemente" },
      { value: 2, short: "2", full: "Moderadamente" },
      { value: 3, short: "3", full: "Bastante" },
      { value: 4, short: "4", full: "Mucho" },
      { value: 5, short: "5", full: "Extremadamente" },
    ],
    computeScore: (a) => a.reduce((s, x) => s + x, 0),
    maxScore: 150,
    minScore: 0,
    bands: [
      { max: 44,  label: "Mínima o ausente",    ...B.mid,  description: "La experiencia reportada tiene poca o nula carga mística. Puede reflejar experiencias más ordinarias." },
      { max: 89,  label: "Leve a moderada",     ...B.teal, description: "Elementos místicos presentes, aunque sin la intensidad completa de una experiencia mística plena." },
      { max: 119, label: "Significativa",       ...B.gold, description: "Experiencia de alta intensidad con elementos claros de unidad, trascendencia y sacralidad." },
      { max: 150, label: "Intensa / Completa",  ...B.mint, description: "Puntaje en el rango de experiencia mística completa (CME), según criterios de Johns Hopkins." },
    ],
    disclaimer: "El MEQ-30 es de uso libre para investigación y clínica (Johns Hopkins University). No evalúa diagnóstico psicopatológico.",
  },
  PERMA: {
    name: "PERMA",
    subtitle: "Bienestar general",
    category: "bienestar",
    cardDescription: "15 preguntas · ~3 min · Evalúa las cinco dimensiones del bienestar: emociones positivas, compromiso, relaciones, significado y logro.",
    accentClass: "text-interactive-text",
    borderClass: "border-brand-mint/40 hover:border-brand-mint",
    btnSelectedClass: "bg-brand-mint border-brand-mint text-brand-night",
    btnHoverClass: "hover:border-brand-mint/50 hover:text-brand-mint",
    barClass: "bg-brand-mint",
    questions: [
      "¿Con qué frecuencia sientes emociones positivas (alegría, gratitud, serenidad)?",
      "En general, ¿qué tan feliz te sientes?",
      "¿Con qué frecuencia disfrutas genuinamente lo que haces?",
      "¿Con qué frecuencia te encuentras completamente absorto/a en lo que haces?",
      "¿Con qué frecuencia el tiempo parece \"volar\" mientras realizas tus actividades?",
      "¿Con qué frecuencia te sientes profundamente involucrado/a en lo que haces?",
      "¿En qué medida recibes apoyo de otras personas cuando lo necesitas?",
      "¿En qué medida te sientes querido/a y amado/a?",
      "¿Qué tan satisfecho/a estás con tus relaciones personales?",
      "En general, ¿qué tan significativa encuentras tu vida?",
      "¿Con qué frecuencia sientes que lo que haces es valioso e importante?",
      "¿Con qué frecuencia tienes la sensación de que tu vida tiene un propósito claro?",
      "¿Con qué frecuencia alcanzas las metas que te propones?",
      "¿Qué tan capaz te sientes de manejar tus responsabilidades?",
      "¿Con qué frecuencia progresas en los objetivos más importantes para ti?",
    ],
    shortLabels: [
      "Emociones positivas", "Felicidad", "Disfrute",
      "Absorción", "Flujo", "Involucramiento",
      "Apoyo recibido", "Amor y pertenencia", "Satisfacción relacional",
      "Sentido de vida", "Valor de lo que hago", "Propósito",
      "Logro de metas", "Capacidad personal", "Progreso",
    ],
    instructions: "Pensando en el último mes, indica en qué medida cada afirmación describe tu experiencia. Usa la escala del 0 al 10:",
    scale: Array.from({ length: 11 }, (_, i) => ({
      value: i,
      short: `${i}`,
      full: i === 0 ? "Nunca / Nada" : i === 5 ? "A veces" : i === 10 ? "Siempre / Totalmente" : `${i}`,
    })),
    computeScore: (a) => a.reduce((s, x) => s + x, 0),
    maxScore: 150,
    minScore: 0,
    bands: [
      { max: 59,  label: "Bienestar muy bajo",  ...B.red,  description: "El bienestar percibido en este momento es significativamente bajo en varias dimensiones." },
      { max: 89,  label: "Bienestar bajo",      ...B.gold, description: "Hay áreas de bienestar que necesitan atención. Las subescalas pueden orientar dónde enfocar." },
      { max: 119, label: "Bienestar moderado",  ...B.teal, description: "Nivel de bienestar dentro del rango promedio, con espacio para fortalecer algunas dimensiones." },
      { max: 139, label: "Bienestar alto",      ...B.mint, description: "Buen nivel de bienestar general. Las dimensiones del PERMA están funcionando de manera sólida." },
      { max: 150, label: "Bienestar muy alto",  ...B.mint, description: "Nivel de florecimiento alto. Las cinco dimensiones del bienestar están muy bien integradas." },
    ],
    subScales: [
      {
        label: "Emociones positivas (P)",
        indices: [0, 1, 2],
        maxScore: 30,
        bands: [
          { max: 10, label: "Bajo",     textClass: B.gold.textClass },
          { max: 18, label: "Moderado", textClass: B.teal.textClass },
          { max: 25, label: "Alto",     textClass: B.mint.textClass },
          { max: 30, label: "Muy alto", textClass: B.mint.textClass },
        ],
      },
      {
        label: "Compromiso (E)",
        indices: [3, 4, 5],
        maxScore: 30,
        bands: [
          { max: 10, label: "Bajo",     textClass: B.gold.textClass },
          { max: 18, label: "Moderado", textClass: B.teal.textClass },
          { max: 25, label: "Alto",     textClass: B.mint.textClass },
          { max: 30, label: "Muy alto", textClass: B.mint.textClass },
        ],
      },
      {
        label: "Relaciones (R)",
        indices: [6, 7, 8],
        maxScore: 30,
        bands: [
          { max: 10, label: "Bajo",     textClass: B.gold.textClass },
          { max: 18, label: "Moderado", textClass: B.teal.textClass },
          { max: 25, label: "Alto",     textClass: B.mint.textClass },
          { max: 30, label: "Muy alto", textClass: B.mint.textClass },
        ],
      },
      {
        label: "Significado (M)",
        indices: [9, 10, 11],
        maxScore: 30,
        bands: [
          { max: 10, label: "Bajo",     textClass: B.gold.textClass },
          { max: 18, label: "Moderado", textClass: B.teal.textClass },
          { max: 25, label: "Alto",     textClass: B.mint.textClass },
          { max: 30, label: "Muy alto", textClass: B.mint.textClass },
        ],
      },
      {
        label: "Logro (A)",
        indices: [12, 13, 14],
        maxScore: 30,
        bands: [
          { max: 10, label: "Bajo",     textClass: B.gold.textClass },
          { max: 18, label: "Moderado", textClass: B.teal.textClass },
          { max: 25, label: "Alto",     textClass: B.mint.textClass },
          { max: 30, label: "Muy alto", textClass: B.mint.textClass },
        ],
      },
    ],
    disclaimer: "El PERMA-Profiler es de uso libre para investigación y clínica (Butler & Kern, 2016). Evalúa bienestar percibido, no diagnóstico clínico.",
  },

  EBI: {
    name: "EBI",
    subtitle: "Avance emocional",
    category: "postsesion",
    cardDescription: "6 preguntas · ~1 min · Evalúa la profundidad del avance emocional vivido en una sesión terapéutica o experiencia de conciencia no ordinaria.",
    accentClass: "text-accent-text",
    borderClass: "border-brand-gold/40 hover:border-brand-gold",
    btnSelectedClass: "bg-brand-gold border-brand-gold text-brand-night",
    btnHoverClass: "hover:border-brand-gold/50 hover:text-brand-gold",
    barClass: "bg-brand-gold",
    questions: [
      "Experimenté un avance o quiebre emocional importante",
      "Confronté emociones difíciles o dolorosas que evitaba",
      "Procesé sentimientos que había estado evitando o suprimiendo",
      "Sentí una liberación o catarsis emocional",
      "Obtuve nuevas perspectivas sobre mis experiencias emocionales o sobre mí mismo/a",
      "Sentí que se produjeron cambios emocionales positivos y duraderos",
    ],
    shortLabels: [
      "Avance emocional", "Confrontación emocional", "Procesamiento evitado",
      "Liberación / catarsis", "Nuevas perspectivas", "Cambios duraderos",
    ],
    instructions: "Pensando en la sesión más reciente, indica en qué medida cada afirmación describe lo que experimentaste:",
    note: "Este instrumento evalúa componentes de avance emocional en el contexto de una sesión terapéutica o experiencia de conciencia no ordinaria.",
    scale: [
      { value: 0, short: "Nada",    full: "En absoluto" },
      { value: 1, short: "Mín.",    full: "Mínimamente" },
      { value: 2, short: "Poco",    full: "Levemente" },
      { value: 3, short: "Algo",    full: "Moderadamente" },
      { value: 4, short: "Bastante", full: "Bastante" },
      { value: 5, short: "Mucho",   full: "Mucho" },
      { value: 6, short: "Ext.",    full: "Extremadamente" },
    ],
    computeScore: (a) => a.reduce((s, x) => s + x, 0),
    maxScore: 36,
    minScore: 0,
    bands: [
      { max: 7,  label: "Mínimo",     ...B.mid,  description: "La sesión no produjo un avance emocional marcado. Puede ser parte del proceso — no todas las sesiones lo generan." },
      { max: 16, label: "Leve",       ...B.teal, description: "Hubo algunos movimientos emocionales, aunque no constituyeron un breakthrough claro." },
      { max: 25, label: "Moderado",   ...B.gold, description: "Se vivió un avance emocional significativo. La integración de lo emergido puede profundizar el efecto." },
      { max: 36, label: "Intenso",    ...B.mint, description: "Experiencia de avance emocional profundo. El acompañamiento en la integración es especialmente valioso aquí." },
    ],
    disclaimer: "El EBI es un instrumento de investigación (Roseman, 2019) para contextos de terapia asistida con psicodélicos. No reemplaza la evaluación clínica.",
  },

  CEQ: {
    name: "CEQ",
    subtitle: "Experiencia desafiante",
    category: "postsesion",
    cardDescription: "26 preguntas · ~5 min · Caracteriza la naturaleza y la intensidad de experiencias difíciles durante una sesión — guía la integración post-sesión.",
    accentClass: "text-foreground/70",
    borderClass: "border-brand-mid/40 hover:border-brand-mid",
    btnSelectedClass: "bg-brand-mid border-brand-mid text-white",
    btnHoverClass: "hover:border-brand-mid/50 hover:opacity-100",
    barClass: "bg-brand-mid",
    questions: [
      "Sentí tristeza o dolor emocional",
      "Lloré o estuve a punto de llorar",
      "Sentí pérdida o duelo",
      "Experimenté un dolor emocional difícil de sostener",
      "Sentí miedo",
      "Sentí ansiedad",
      "Sentí pánico",
      "Me sentí aterrorizado/a",
      "Sentí que estaba muriendo o que algo en mí moría",
      "Tuve miedo de morir durante la experiencia",
      "Creí que realmente podría morir",
      "Sentí terror extremo",
      "Sentí que estaba perdiendo la razón",
      "Tuve miedo de perder el control de mis pensamientos o acciones",
      "Tuve miedo de volverme loco/a",
      "Creí que me estaba volviendo insano/a",
      "Me sentí completamente solo/a",
      "Me sentí desconectado/a del mundo",
      "Me sentí atrapado/a o sin salida",
      "Quería ayuda pero no podía pedirla o recibirla",
      "Sentí malestar físico intenso",
      "Sentí náuseas",
      "Tuve dolor de cabeza u otro dolor físico",
      "Tuve sensaciones físicas muy angustiantes",
      "Desconfié de las intenciones de otras personas",
      "Sentí que otros estaban en mi contra",
    ],
    shortLabels: [
      "Tristeza", "Llanto", "Pérdida/duelo", "Dolor emocional",
      "Miedo", "Ansiedad", "Pánico", "Terror",
      "Sensación de muerte", "Miedo a morir", "Creer que moría", "Terror extremo",
      "Perder la razón", "Perder el control", "Miedo a la locura", "Creerse insano/a",
      "Soledad", "Desconexión", "Sentirse atrapado/a", "Sin poder pedir ayuda",
      "Malestar físico", "Náuseas", "Dolor físico", "Sensaciones angustiantes",
      "Desconfianza", "Sentirse amenazado/a",
    ],
    instructions: "Pensando en la sesión que acabas de completar, indica en qué medida cada afirmación describe algo que experimentaste:",
    note: "Algunas de estas experiencias pueden haber sido muy intensas. El CEQ busca capturarlas con precisión para guiar el proceso de integración.",
    scale: [
      { value: 0, short: "Nada",   full: "Ninguno / Nada" },
      { value: 1, short: "Leve",   full: "Leve" },
      { value: 2, short: "Mod.",   full: "Moderado" },
      { value: 3, short: "Fuerte", full: "Fuerte" },
      { value: 4, short: "Muy ft.", full: "Muy fuerte" },
      { value: 5, short: "Ext.",   full: "Extremo" },
    ],
    computeScore: (a) => a.reduce((s, x) => s + x, 0),
    maxScore: 130,
    minScore: 0,
    bands: [
      { max: 15,  label: "Mínima",    ...B.mint, description: "La sesión tuvo muy pocas experiencias desafiantes. El proceso fue en su mayor parte fluido." },
      { max: 35,  label: "Leve",      ...B.teal, description: "Algunos momentos difíciles, manejables en contexto. Las subescalas señalan qué dominios merecen atención." },
      { max: 65,  label: "Moderada",  ...B.gold, description: "Desafíos significativos durante la sesión. La integración guiada con el terapeuta es especialmente importante." },
      { max: 130, label: "Intensa",   ...B.red,  description: "Experiencia muy desafiante. El trabajo de integración es fundamental para convertir lo difícil en material de crecimiento." },
    ],
    subScales: [
      {
        label: "Dolor emocional",
        indices: [0, 1, 2, 3],
        maxScore: 20,
        bands: [
          { max: 3,  label: "Mínimo",   textClass: B.mint.textClass },
          { max: 8,  label: "Leve",     textClass: B.teal.textClass },
          { max: 14, label: "Moderado", textClass: B.gold.textClass },
          { max: 20, label: "Intenso",  textClass: B.red.textClass },
        ],
      },
      {
        label: "Miedo",
        indices: [4, 5, 6, 7],
        maxScore: 20,
        bands: [
          { max: 3,  label: "Mínimo",   textClass: B.mint.textClass },
          { max: 8,  label: "Leve",     textClass: B.teal.textClass },
          { max: 14, label: "Moderado", textClass: B.gold.textClass },
          { max: 20, label: "Intenso",  textClass: B.red.textClass },
        ],
      },
      {
        label: "Muerte",
        indices: [8, 9, 10, 11],
        maxScore: 20,
        bands: [
          { max: 3,  label: "Mínimo",   textClass: B.mint.textClass },
          { max: 8,  label: "Leve",     textClass: B.teal.textClass },
          { max: 14, label: "Moderado", textClass: B.gold.textClass },
          { max: 20, label: "Intenso",  textClass: B.red.textClass },
        ],
      },
      {
        label: "Locura",
        indices: [12, 13, 14, 15],
        maxScore: 20,
        bands: [
          { max: 3,  label: "Mínimo",   textClass: B.mint.textClass },
          { max: 8,  label: "Leve",     textClass: B.teal.textClass },
          { max: 14, label: "Moderado", textClass: B.gold.textClass },
          { max: 20, label: "Intenso",  textClass: B.red.textClass },
        ],
      },
      {
        label: "Aislamiento",
        indices: [16, 17, 18, 19],
        maxScore: 20,
        bands: [
          { max: 3,  label: "Mínimo",   textClass: B.mint.textClass },
          { max: 8,  label: "Leve",     textClass: B.teal.textClass },
          { max: 14, label: "Moderado", textClass: B.gold.textClass },
          { max: 20, label: "Intenso",  textClass: B.red.textClass },
        ],
      },
      {
        label: "Malestar físico",
        indices: [20, 21, 22, 23],
        maxScore: 20,
        bands: [
          { max: 3,  label: "Mínimo",   textClass: B.mint.textClass },
          { max: 8,  label: "Leve",     textClass: B.teal.textClass },
          { max: 14, label: "Moderado", textClass: B.gold.textClass },
          { max: 20, label: "Intenso",  textClass: B.red.textClass },
        ],
      },
      {
        label: "Paranoia",
        indices: [24, 25],
        maxScore: 10,
        bands: [
          { max: 1, label: "Mínima",   textClass: B.mint.textClass },
          { max: 4, label: "Leve",     textClass: B.teal.textClass },
          { max: 7, label: "Moderada", textClass: B.gold.textClass },
          { max: 10, label: "Intensa", textClass: B.red.textClass },
        ],
      },
    ],
    disclaimer: "El CEQ es de uso libre para investigación (Barrett et al., 2016, Johns Hopkins). No reemplaza la evaluación ni el acompañamiento clínico.",
  },

  CBI: {
    name: "CBI",
    subtitle: "Burnout",
    category: "clinico",
    cardDescription: "19 preguntas · ~4 min · Evalúa el agotamiento personal, laboral y relacionado con clientes/pacientes.",
    accentClass: "text-accent-text",
    borderClass: "border-brand-gold/30",
    btnSelectedClass: "bg-brand-gold/20 border border-brand-gold text-brand-gold",
    btnHoverClass: "hover:bg-brand-gold/10 hover:border-brand-gold/40",
    barClass: "bg-brand-gold",
    instructions: "Piensa en cómo te has sentido en los últimos meses. Elige la opción que mejor describe con qué frecuencia o en qué medida experimenta cada afirmación.",
    scale: [
      { value: 0, short: "Nunca",   full: "Nunca / casi nunca" },
      { value: 25, short: "Poco",   full: "Raramente" },
      { value: 50, short: "A veces", full: "A veces" },
      { value: 75, short: "Frecuente", full: "Frecuentemente" },
      { value: 100, short: "Siempre", full: "Siempre / casi siempre" },
    ],
    questions: [
      "¿Con qué frecuencia te sientes fatigado/a?",
      "¿Con qué frecuencia te sientes físicamente agotado/a?",
      "¿Con qué frecuencia te sientes emocionalmente exhausto/a?",
      "¿Con qué frecuencia piensas 'no puedo más'?",
      "¿Con qué frecuencia te sientes desgastado/a?",
      "¿Con qué frecuencia te sientes débil y susceptible a enfermarte?",
      "¿Tu trabajo te agota emocionalmente?",
      "¿Te sientes extenuado/a al final de un día de trabajo?",
      "¿Tu trabajo te frustra?",
      "¿Te sientes quemado/a por tu trabajo?",
      "¿Sientes que inviertes más de lo que obtienes en tu trabajo?",
      "¿Estás cansado/a de tu trabajo?",
      "¿Alguna vez te preguntas cuánto tiempo más podrás aguantar este trabajo?",
      "¿Encuentras difícil trabajar con clientes/pacientes?",
      "¿Trabajar con clientes/pacientes te agota?",
      "¿A veces desearías no tener que tratar con clientes/pacientes?",
      "¿Tu trabajo con clientes/pacientes te irrita?",
      "¿Sientes que das más de lo que recibes al trabajar con clientes/pacientes?",
      "¿Estás cansado/a de trabajar con clientes/pacientes?",
    ],
    shortLabels: ["Nunca", "Raramente", "A veces", "Frecuente", "Siempre"],
    computeScore: (answers) => Math.round(answers.reduce((s, a) => s + a, 0) / answers.length),
    maxScore: 100,
    minScore: 0,
    bands: [
      { max: 49,  label: "Sin burnout",       description: "Niveles de agotamiento dentro de lo normal.", ...B.mint,  barClass: B.mint.barClass },
      { max: 74,  label: "Burnout moderado",  description: "Señales importantes de desgaste que merecen atención.", ...B.gold, barClass: B.gold.barClass },
      { max: 100, label: "Burnout severo",    description: "Agotamiento intenso: se recomienda intervención.", ...B.red,  barClass: B.red.barClass },
    ],
    subScales: [
      {
        label: "Agotamiento personal",
        indices: [0, 1, 2, 3, 4, 5],
        maxScore: 100,
        bands: [
          { max: 49,  label: "Bajo",     textClass: B.mint.textClass },
          { max: 74,  label: "Moderado", textClass: B.gold.textClass },
          { max: 100, label: "Alto",     textClass: B.red.textClass },
        ],
      },
      {
        label: "Burnout laboral",
        indices: [6, 7, 8, 9, 10, 11, 12],
        maxScore: 100,
        bands: [
          { max: 49,  label: "Bajo",     textClass: B.mint.textClass },
          { max: 74,  label: "Moderado", textClass: B.gold.textClass },
          { max: 100, label: "Alto",     textClass: B.red.textClass },
        ],
      },
      {
        label: "Burnout con clientes",
        indices: [13, 14, 15, 16, 17, 18],
        maxScore: 100,
        bands: [
          { max: 49,  label: "Bajo",     textClass: B.mint.textClass },
          { max: 74,  label: "Moderado", textClass: B.gold.textClass },
          { max: 100, label: "Alto",     textClass: B.red.textClass },
        ],
      },
    ],
    disclaimer: "El CBI (Copenhagen Burnout Inventory) es de dominio público (Kristensen et al., 2005). No reemplaza la evaluación clínica.",
  },

  AQ10: {
    name: "AQ-10",
    subtitle: "Tamizaje autismo",
    category: "neurodiversidad",
    cardDescription: "10 preguntas · ~2 min · Tamizaje breve del espectro autista en adultos. Punto de corte ≥6.",
    accentClass: "text-interactive-text",
    borderClass: "border-brand-teal/30",
    btnSelectedClass: "bg-brand-teal/20 border border-brand-teal text-brand-teal",
    btnHoverClass: "hover:bg-brand-teal/10 hover:border-brand-teal/40",
    barClass: "bg-brand-teal",
    instructions: "Indica en qué medida estás de acuerdo con cada afirmación. No hay respuestas correctas o incorrectas.",
    scale: [
      { value: 0, short: "TD",          full: "Totalmente de acuerdo" },
      { value: 1, short: "De acuerdo",  full: "De acuerdo" },
      { value: 2, short: "En desac.",   full: "En desacuerdo" },
      { value: 3, short: "Totalmente",  full: "Totalmente en desacuerdo" },
    ],
    questions: [
      "Noto cuando alguien en un grupo está incómodo o molesto.",
      "Prefiero hacer las cosas de la misma manera una y otra vez.",
      "Si trato de imaginar algo, encuentro muy fácil crearme una imagen mental.",
      "Me absorbo fácilmente en las cosas.",
      "Noto detalles pequeños que otros no notan.",
      "Sé cuándo es el turno de hablar en una conversación.",
      "Cuando leo una historia, me resulta difícil descubrir las intenciones de los personajes.",
      "Me gustan las reuniones sociales y las ocasiones para hablar con otras personas.",
      "Me resulta fácil hacer más de una cosa a la vez.",
      "Cuando tengo una conversación con alguien, presto atención al lenguaje corporal.",
    ],
    shortLabels: ["Totalmente de acuerdo", "De acuerdo", "En desacuerdo", "Totalmente en desacuerdo"],
    computeScore: (answers) => {
      const reverseIndices = [1, 2, 3, 4, 5, 8];
      return answers.reduce((sum, val, i) => {
        const score = reverseIndices.includes(i)
          ? (val <= 1 ? 1 : 0)
          : (val >= 2 ? 1 : 0);
        return sum + score;
      }, 0);
    },
    maxScore: 10,
    minScore: 0,
    bands: [
      { max: 5,  label: "Por debajo del umbral", description: "Puntuación por debajo del umbral de tamizaje.", ...B.mint, barClass: B.mint.barClass },
      { max: 10, label: "Positivo (≥6)",          description: "Resultado positivo en el tamizaje; se recomienda evaluación diagnóstica.", ...B.teal, barClass: B.teal.barClass },
    ],
    disclaimer: "El AQ-10 es una herramienta de tamizaje, no diagnóstica (Allison et al., 2012, Cambridge). Un resultado ≥6 sugiere derivación para evaluación formal.",
  },

  AQ50: {
    name: "AQ-50",
    subtitle: "Autismo (completo)",
    category: "neurodiversidad",
    cardDescription: "50 preguntas · ~10 min · Versión completa del Autism Spectrum Quotient. Punto de corte ≥32.",
    accentClass: "text-interactive-text",
    borderClass: "border-brand-teal/30",
    btnSelectedClass: "bg-brand-teal/20 border border-brand-teal text-brand-teal",
    btnHoverClass: "hover:bg-brand-teal/10 hover:border-brand-teal/40",
    barClass: "bg-brand-teal",
    instructions: "Indica en qué medida estás de acuerdo con cada afirmación. No hay respuestas correctas o incorrectas.",
    scale: [
      { value: 0, short: "TD",         full: "Totalmente de acuerdo" },
      { value: 1, short: "De acuerdo", full: "De acuerdo" },
      { value: 2, short: "En desac.",  full: "En desacuerdo" },
      { value: 3, short: "Totalmente", full: "Totalmente en desacuerdo" },
    ],
    questions: [
      "Prefiero hacer las cosas con otras personas que solo/a.",
      "Prefiero hacer las cosas de la misma manera una y otra vez.",
      "Si trato de imaginar algo, encuentro muy fácil crearme una imagen mental.",
      "Me absorbo fácilmente en las cosas.",
      "Noto detalles pequeños que otros no notan.",
      "En situaciones sociales, no sé de qué hablar.",
      "Cuando leo una historia, me resulta difícil descubrir las intenciones de los personajes.",
      "Me gustan las reuniones sociales y las ocasiones para hablar con otras personas.",
      "Cuando trato de imaginar algo, encuentro muy fácil crear una imagen mental.",
      "Me resulta difícil captar las intenciones de las personas.",
      "Me encanta coleccionar información sobre categorías de cosas (por ejemplo, tipos de coches, tipos de pájaros, tipos de trenes, tipos de plantas, etc.).",
      "Me resulta difícil hacer más de una cosa a la vez.",
      "Cuando tengo una conversación con alguien, presto atención al lenguaje corporal.",
      "Tengo tendencia a notar ruidos que otros no notan.",
      "Prefiero ir a una biblioteca que a una fiesta.",
      "Encuentro muy difícil el guión de conversaciones sociales.",
      "Generalmente me resulta difícil hacer nuevos amigos/as.",
      "Tiendo a hacer las cosas de la misma manera repetidamente.",
      "Me resulta fácil mantener el hilo de varias conversaciones a la vez.",
      "Cuando noto una pequeña variación en una rutina cotidiana, me perturba.",
      "Me resulta fácil distinguir el tono de voz de una persona.",
      "Noto las sutilezas en las expresiones faciales de las personas.",
      "Prefiero hacer las cosas de una manera fija y rutinaria.",
      "Encuentro fácil combinar las cosas para crear algo nuevo.",
      "Me resulta difícil saber por dónde empezar en una conversación.",
      "Las sutilezas del lenguaje no siempre son claras para mí.",
      "Me concentro más en el cuadro general que en los detalles.",
      "Si hay una interrupción, puedo volver a la tarea que estaba haciendo muy rápidamente.",
      "Suelo ser la última persona en entender el chiste en una conversación.",
      "Me resulta fácil realizar varias tareas a la vez.",
      "Cuando hablo por teléfono, no estoy seguro/a de cuándo es mi turno de hablar.",
      "Me gustan hacer las cosas espontáneamente.",
      "Me preocupo por los plazos.",
      "Disfruto haciendo cosas de forma espontánea.",
      "Disfruto tanto de las conversaciones informales como de las más serias.",
      "Noto cuando alguien en un grupo está incómodo o molesto.",
      "Encuentro fácil leer entre líneas en las conversaciones.",
      "Me concentro en los detalles más que en el cuadro general.",
      "Me resulta difícil hablar con personas que no conozco bien.",
      "Disfruto conociendo gente nueva.",
      "Si algo es ligeramente diferente de lo que espero, me perturba mucho.",
      "Sé cómo interpretar las intenciones de las personas.",
      "Me resulta fácil hacer más de una cosa a la vez.",
      "Me gustan mucho los rituales cotidianos y me molesta que se alteren.",
      "Puedo hacer con facilidad una buena lista cuando me propongo hacer varias cosas.",
      "Me resulta fácil descifrar lo que alguien piensa o siente solo mirando su cara.",
      "Si se interrumpe mi rutina, me resulta muy difícil retomar lo que estaba haciendo.",
      "Disfruto de las conversaciones sociales.",
      "Soy bueno/a con las cifras.",
      "Me resulta difícil recordar números de teléfono.",
    ],
    shortLabels: ["Totalmente de acuerdo", "De acuerdo", "En desacuerdo", "Totalmente en desacuerdo"],
    computeScore: (answers) => {
      const reverseIndices = [0, 2, 7, 9, 10, 13, 14, 16, 23, 24, 26, 27, 28, 29, 30, 31, 33, 35, 36, 37, 39, 43, 46, 47, 48, 49];
      return answers.reduce((sum, val, i) => {
        const score = reverseIndices.includes(i)
          ? (val <= 1 ? 1 : 0)
          : (val >= 2 ? 1 : 0);
        return sum + score;
      }, 0);
    },
    maxScore: 50,
    minScore: 0,
    bands: [
      { max: 31, label: "Por debajo del umbral", description: "Puntuación por debajo del punto de corte clínico.", ...B.mint, barClass: B.mint.barClass },
      { max: 50, label: "Positivo (≥32)",         description: "Resultado positivo; se recomienda evaluación diagnóstica formal.", ...B.teal, barClass: B.teal.barClass },
    ],
    disclaimer: "El AQ-50 es una herramienta de investigación y tamizaje (Baron-Cohen et al., 2001, Cambridge). No es diagnóstico. Un puntaje ≥32 sugiere derivación para evaluación especializada.",
  },

  CATQ: {
    name: "CAT-Q",
    subtitle: "Enmascaramiento autista",
    category: "neurodiversidad",
    cardDescription: "25 preguntas · ~5 min · Mide el enmascaramiento de rasgos autistas en 3 dimensiones: compensación, asimilación y camuflaje.",
    accentClass: "text-foreground/70",
    borderClass: "border-brand-mid/30",
    btnSelectedClass: "bg-brand-mid/20 border border-brand-mid text-brand-mid",
    btnHoverClass: "hover:bg-brand-mid/10 hover:border-brand-mid/40",
    barClass: "bg-brand-mid",
    instructions: "Indica en qué medida cada afirmación te describe a ti. No hay respuestas correctas ni incorrectas.",
    scale: [
      { value: 1, short: "1",  full: "Totalmente en desacuerdo" },
      { value: 2, short: "2",  full: "En desacuerdo" },
      { value: 3, short: "3",  full: "Algo en desacuerdo" },
      { value: 4, short: "4",  full: "Ni de acuerdo ni en desacuerdo" },
      { value: 5, short: "5",  full: "Algo de acuerdo" },
      { value: 6, short: "6",  full: "De acuerdo" },
      { value: 7, short: "7",  full: "Totalmente de acuerdo" },
    ],
    questions: [
      "Cuando estoy en una situación social, imito los comportamientos de otras personas para encajar.",
      "Uso guiones aprendidos (por ejemplo, formas de decir hola, hablar sobre el tiempo) cuando hablo con personas.",
      "En situaciones sociales, copio los movimientos del cuerpo y las expresiones faciales de los demás.",
      "Aprendo naturalmente cómo comportarme en situaciones sociales imitando a los demás.",
      "Me preparo temas de conversación, preguntas y bromas con anticipación para poder usarlos en conversaciones.",
      "Cuando estoy en una situación social, encuentro difícil saber qué decir o hacer.",
      "En situaciones sociales, me siento frustrado/a cuando estoy con personas nuevas.",
      "Me resulta difícil saber cómo comportarme en situaciones sociales, así que presto atención a cómo actúan los demás e intento hacer lo mismo.",
      "En situaciones sociales, observo cómo se comportan los demás y luego los copio.",
      "Me siento presionado/a a comportarme de cierta manera en situaciones sociales.",
      "Cuando estoy en grupos sociales, observo qué hacen los demás y lo adapto.",
      "Aprendo cómo ser sociable observando a los demás.",
      "Practico y repito mis expresiones faciales y mi lenguaje corporal para parecer más natural cuando socializo.",
      "Encuentro difícil leer las señales no verbales de los demás, así que les presto mucha atención.",
      "Con frecuencia no sé cómo comportarme socialmente y tengo que aprenderlo 'artificialmente'.",
      "Encuentro los entornos sociales estresantes, así que preparo qué voy a decir con anticipación.",
      "Pienso cuidadosamente sobre lo que debo decir antes de hablar.",
      "Cuando hablo con alguien, pienso mucho en lo que estoy haciendo con mi cara y con mi cuerpo.",
      "Tengo que suprimir tics o comportamientos repetitivos en situaciones sociales.",
      "Me siento menos bien con mis intereses cuando estoy en un entorno social porque temo que los demás los encuentren raros.",
      "Me oculto cuando tengo ansiedad o estrés para que los demás no se den cuenta.",
      "Me ajusto y adapto mi comportamiento dependiendo de con quién estoy.",
      "Actúo de una manera diferente a cómo me siento por dentro para encajar con los demás.",
      "Siento que tengo que esforzarme mucho en situaciones sociales para que a los demás les guste.",
      "Actúo de una manera que no refleja cómo me siento realmente por dentro para encajar socialmente.",
    ],
    shortLabels: ["1", "2", "3", "4", "5", "6", "7"],
    computeScore: (answers) => answers.reduce((s, a) => s + a, 0),
    maxScore: 175,
    minScore: 25,
    bands: [
      { max: 100, label: "Bajo enmascaramiento",      description: "Niveles bajos de camuflaje de rasgos autistas.", ...B.mint, barClass: B.mint.barClass },
      { max: 130, label: "Enmascaramiento moderado",  description: "Niveles moderados de compensación y camuflaje social.", ...B.gold, barClass: B.gold.barClass },
      { max: 175, label: "Alto enmascaramiento",      description: "Niveles elevados de camuflaje; puede asociarse a agotamiento.", ...B.red, barClass: B.red.barClass },
    ],
    subScales: [
      {
        label: "Compensación",
        indices: [0, 1, 2, 3, 4, 7, 8, 10, 11, 12, 13, 14],
        maxScore: 84,
        bands: [
          { max: 40,  label: "Bajo",     textClass: B.mint.textClass },
          { max: 65,  label: "Moderado", textClass: B.gold.textClass },
          { max: 84,  label: "Alto",     textClass: B.red.textClass },
        ],
      },
      {
        label: "Asimilación",
        indices: [5, 6, 9, 15, 16, 17, 18, 19, 20],
        maxScore: 63,
        bands: [
          { max: 30,  label: "Bajo",     textClass: B.mint.textClass },
          { max: 48,  label: "Moderado", textClass: B.gold.textClass },
          { max: 63,  label: "Alto",     textClass: B.red.textClass },
        ],
      },
      {
        label: "Camuflaje",
        indices: [21, 22, 23, 24],
        maxScore: 28,
        bands: [
          { max: 13,  label: "Bajo",     textClass: B.mint.textClass },
          { max: 21,  label: "Moderado", textClass: B.gold.textClass },
          { max: 28,  label: "Alto",     textClass: B.red.textClass },
        ],
      },
    ],
    disclaimer: "El CAT-Q se publicó bajo licencia Creative Commons CC-BY 4.0 (Hull et al., 2019, Journal of Autism and Developmental Disorders), que permite su uso y reproducción con atribución. No es diagnóstico; evalúa estrategias de enmascaramiento.",
  },

  ASRS: {
    name: "ASRS-v1.1",
    subtitle: "TDAH en adultos",
    category: "neurodiversidad",
    cardDescription: "18 preguntas · ~4 min · Escala de la OMS para el TDAH en adultos. Las 6 primeras preguntas (Parte A) son las más sensibles.",
    accentClass: "text-interactive-text",
    borderClass: "border-brand-mint/30",
    btnSelectedClass: "bg-brand-mint/20 border border-brand-mint text-brand-mint",
    btnHoverClass: "hover:bg-brand-mint/10 hover:border-brand-mint/40",
    barClass: "bg-brand-mint",
    instructions: "Piensa en los últimos 6 meses. ¿Con qué frecuencia has tenido los siguientes problemas?",
    scale: [
      { value: 0, short: "Nunca",   full: "Nunca" },
      { value: 1, short: "Raro",    full: "Raramente" },
      { value: 2, short: "A veces", full: "A veces" },
      { value: 3, short: "Seguido", full: "Con frecuencia" },
      { value: 4, short: "Siempre", full: "Muy frecuentemente" },
    ],
    questions: [
      "¿Con qué frecuencia tienes dificultades para completar los detalles finales de un proyecto una vez que ya has superado las partes desafiantes?",
      "¿Con qué frecuencia tienes dificultades para poner las cosas en orden cuando tienes que hacer una tarea que requiere organización?",
      "¿Con qué frecuencia tienes problemas para recordar citas u obligaciones?",
      "Cuando tienes que hacer algo que requiere mucha concentración, ¿con qué frecuencia evitas o pospones comenzarlo?",
      "¿Con qué frecuencia retuerces o agitas las manos o los pies cuando tienes que estar sentado/a mucho tiempo?",
      "¿Con qué frecuencia te sientes demasiado activo/a e impulsado/a a hacer cosas, como si te empujara un motor?",
      "¿Con qué frecuencia cometes errores por descuido cuando tienes que trabajar en un proyecto aburrido o difícil?",
      "¿Con qué frecuencia tienes dificultades para mantener la atención cuando haces trabajo aburrido o repetitivo?",
      "¿Con qué frecuencia tienes dificultades para concentrarte en lo que te dicen las personas, incluso cuando te hablan directamente?",
      "¿Con qué frecuencia extravías objetos o tienes dificultades para encontrar las cosas en casa o en el trabajo?",
      "¿Con qué frecuencia te distraes con la actividad o el ruido de tu alrededor?",
      "¿Con qué frecuencia te vas del asiento en reuniones u otras situaciones en las que se supone que debes permanecer sentado/a?",
      "¿Con qué frecuencia te sientes agitado/a o intranquilo/a?",
      "¿Con qué frecuencia tienes dificultades para relajarte y descansar cuando tienes tiempo libre?",
      "¿Con qué frecuencia te encuentras hablando demasiado cuando estás en una situación social?",
      "Cuando estás en una conversación, ¿con qué frecuencia terminas las frases de las personas con las que hablas antes de que puedan terminar?",
      "¿Con qué frecuencia tienes dificultades para esperar en situaciones en las que debes esperar tu turno?",
      "¿Con qué frecuencia interrumpes a los demás cuando están ocupados?",
    ],
    shortLabels: ["Nunca", "Raramente", "A veces", "Frecuente", "Muy frecuente"],
    computeScore: (answers) => answers.reduce((s, a) => s + a, 0),
    maxScore: 72,
    minScore: 0,
    bands: [
      { max: 23, label: "Sin indicadores",      description: "Puntaje por debajo del umbral de tamizaje.", ...B.mint, barClass: B.mint.barClass },
      { max: 72, label: "Indicadores de TDAH",  description: "Puntaje elevado; se recomienda evaluación clínica.", ...B.teal, barClass: B.teal.barClass },
    ],
    subScales: [
      {
        label: "Parte A (diagnóstica)",
        indices: [0, 1, 2, 3, 4, 5],
        maxScore: 24,
        bands: [
          { max: 13, label: "Bajo",     textClass: B.mint.textClass },
          { max: 24, label: "Positivo", textClass: B.teal.textClass },
        ],
      },
      {
        label: "Parte B",
        indices: [6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17],
        maxScore: 48,
        bands: [
          { max: 24, label: "Bajo",     textClass: B.mint.textClass },
          { max: 48, label: "Elevado",  textClass: B.teal.textClass },
        ],
      },
    ],
    note: "La Parte A (ítems 1–6) es la sección de tamizaje más sensible. Cuatro o más respuestas en la zona sombreada (≥2 para ítems 1–3, ≥3 para ítems 4–6) sugieren TDAH en adultos.",
    disclaimer: "El ASRS-v1.1 es de dominio público (OMS / Kessler et al., 2005). No es diagnóstico; el resultado debe ser evaluado por un profesional.",
  },
};

export function getBand(testId: TestId, score: number): TestConfig["bands"][0] {
  const config = TEST_CONFIGS[testId];
  return config.bands.find((b) => score <= b.max) ?? config.bands[config.bands.length - 1];
}

export function getSubScaleScore(sub: SubScale, answers: number[]): number {
  const raw = sub.indices.reduce((s, i) => s + (answers[i] ?? 0), 0);
  return raw * (sub.multiplier ?? 1);
}

export function getSubScaleBand(sub: SubScale, score: number) {
  return sub.bands.find((b) => score <= b.max) ?? sub.bands[sub.bands.length - 1];
}
